version: '3.9'
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      DB_TYPE: postgres
      PG_USER: postgres
      PG_PASSWORD: secret
      PG_DB: postgres
      PG_PORT: 5432
      PG_HOST: localhost
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  dbdata:
    driver: local

networks:
  node-network:
    driver: bridge


